// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mybackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bond", b =>
                {
                    b.Property<int>("SecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecurityId"));

                    b.Property<double>("AskPrice")
                        .HasColumnType("float");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AverageVolume30Day")
                        .HasColumnType("bigint");

                    b.Property<string>("BBGTicker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BBGUniqueID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BidPrice")
                        .HasColumnType("float");

                    b.Property<string>("BloombergIndustryGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloombergIndustrySector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloombergIndustrySubGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CallNotificationMaxDays")
                        .HasColumnType("int");

                    b.Property<double>("CallPrice")
                        .HasColumnType("float");

                    b.Property<bool>("CallableFlag")
                        .HasColumnType("bit");

                    b.Property<double>("Cap")
                        .HasColumnType("float");

                    b.Property<double>("Convexity")
                        .HasColumnType("float");

                    b.Property<string>("CountryOfIssuance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Coupon")
                        .HasColumnType("float");

                    b.Property<string>("CouponFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstCouponDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FixToFloatFlag")
                        .HasColumnType("bit");

                    b.Property<double>("Floor")
                        .HasColumnType("float");

                    b.Property<bool>("HasPosition")
                        .HasColumnType("bit");

                    b.Property<double>("HighPrice")
                        .HasColumnType("float");

                    b.Property<string>("ISIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LastPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("LowPrice")
                        .HasColumnType("float");

                    b.Property<double>("MacaulayDuration")
                        .HasColumnType("float");

                    b.Property<DateTime>("Maturity")
                        .HasColumnType("datetime2");

                    b.Property<double>("OpenPrice")
                        .HasColumnType("float");

                    b.Property<string>("PFAssetClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFCreditRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFInstrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFLiquidityProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFMaturity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFNAICSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFSubAssetClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PenultimateCouponDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PricingFactor")
                        .HasColumnType("float");

                    b.Property<DateTime>("PutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PutNotificationMaxDays")
                        .HasColumnType("int");

                    b.Property<double>("PutPrice")
                        .HasColumnType("float");

                    b.Property<bool>("PutableFlag")
                        .HasColumnType("bit");

                    b.Property<string>("ResetFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEDOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Spread")
                        .HasColumnType("float");

                    b.Property<double>("TradingFactor")
                        .HasColumnType("float");

                    b.Property<double>("Volatility30D")
                        .HasColumnType("float");

                    b.Property<double>("Volatility90D")
                        .HasColumnType("float");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("SecurityId");

                    b.ToTable("Bonds");
                });

            modelBuilder.Entity("Equity", b =>
                {
                    b.Property<int>("SecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecurityId"));

                    b.Property<string>("ADRUnderlyingCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADRUnderlyingTicker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AskPrice")
                        .HasColumnType("float");

                    b.Property<long>("AverageVolume20D")
                        .HasColumnType("bigint");

                    b.Property<string>("BBGGlobalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BBGIndustrySubGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BBGUniqueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Beta")
                        .HasColumnType("float");

                    b.Property<double>("BidPrice")
                        .HasColumnType("float");

                    b.Property<string>("BloombergIndustryGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloombergSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloombergTicker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloombergUniqueID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ClosePrice")
                        .HasColumnType("float");

                    b.Property<string>("CountryOfIncorporation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfIssuance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DividendAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DividendDeclaredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DividendExDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DividendPayDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DividendRecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DividendType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPosition")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IPODate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsADRFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActiveSecurity")
                        .HasColumnType("bit");

                    b.Property<string>("IssueCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LastPrice")
                        .HasColumnType("float");

                    b.Property<int>("LotSize")
                        .HasColumnType("int");

                    b.Property<double>("OpenPrice")
                        .HasColumnType("float");

                    b.Property<double>("PERatio")
                        .HasColumnType("float");

                    b.Property<string>("PFAssetClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFCreditRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFInstrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFLiquidityProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFMaturity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFNAICSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFSubAssetClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PricingCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReturnYTD")
                        .HasColumnType("float");

                    b.Property<string>("RiskCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEDOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettleDays")
                        .HasColumnType("int");

                    b.Property<int>("SharesPerADR")
                        .HasColumnType("int");

                    b.Property<double>("ShortInterest")
                        .HasColumnType("float");

                    b.Property<string>("TickerAndExchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalSharesOutstanding")
                        .HasColumnType("bigint");

                    b.Property<string>("TradingCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volatility90D")
                        .HasColumnType("float");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<int>("VotingRightsPerShare")
                        .HasColumnType("int");

                    b.HasKey("SecurityId");

                    b.ToTable("Equities");
                });
#pragma warning restore 612, 618
        }
    }
}
